services:
  frontend:
    build:
      context: ./Frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    build:
      context: ./SolarWatch
      dockerfile: Dockerfile
    environment:
      - CONNECTIONSTRINGS__DEFAULT=Server=localhost,11433;Database=SolarWatch;User Id=sa;Password=pwd;Encrypt=false;
    ports:
      - 8080:8080
  
