services:
  frontend:
    build:
      context: Frontend/vite-project
    ports:
      - 3000:3000
        
  backend:
    build:
      context: SolarWatch
    env_file:
      - .env
    ports:
      - 8080:8080
    
  db:
    image: mcr.microsoft.com/mssql/server
    env_file:
      - .env
    ports:
      - 11433:1433
  
