services:
  frontend:
    build:
      context: ./Frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    build:
      context: ./SolarWatch
      dockerfile: Dockerfile
    environment:
      - CONNECTIONSTRINGS__DEFAULT=Server=db;User Id=sa;Password=Kokikutya0123!;Encrypt=false;
    ports:
      - 8080:8080
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kokikutya0123!
    ports:
      - 1433:1433
