services:
  frontend:
    build:
      context: Frontend/vite-project
    ports:
      - "4000:4000"
        
  backend:
    build:
<<<<<<< HEAD
      context: SolarWatch
=======
      context: SolarWatch/
>>>>>>> main
    env_file:
      - .env
    ports:
      - "8080:8080"
    
  db:
    image: mcr.microsoft.com/mssql/server
    env_file:
      - .env
    ports:
      - "1433:1433"
