# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up environment variables
      run: |
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWTSECRETKEY=${{ secrets.JWTSECRETKEY }}" >> $GITHUB_ENV
          echo "VALID_AUDIENCE=${{ secrets.VALIDAUDIENCE }}" >> $GITHUB_ENV
          echo "VALID_ISSUER=${{ secrets.VALIDISSUER }}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env: 
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      run: dotnet test --no-build --verbosity normal

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username
          password: ${{ secrets.DOCKER_TOKEN }}    # DockerHub Access Token
          
    - name: Build and Push Docker images using Docker Compose
      run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
